### ISSUE TITLE
Bug with havdalah

### ISSUE THREAD

**Issue by ShimonMimoun** [shacharbuda/ShabTime#7]
Bug : havdalah not view

**Comment by shacharbuda** [comment]
Hi Shimon,
Thank you for openning this issue! I'm excited to see people using the app

Regarding the bug, as we currently use an api, and the bug seems to go from this direction (Havdala is simply not coming in the json), I only added a bug report on console and a nicer notification in havdala text ('N/A' instead of empty box).
I will try to check out if problem proceed next week (it might happened now because of many events on this shabbat[hannuka, rosh chodesh...])
Thanks again for commenting!

**Comment by ShimonMimoun** [comment]
Hi Sacha
yes i use it and it helps me a lot.thank you for sharing this code.
I think about it too, because the official site does not currently display the time of Shabbat exit.
Maybe it will work out at the end of the week

**Comment by shacharbuda** [comment]
Seems like problem solved :)
